# Generated by Django 4.2.7 on 2024-03-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ecoactivity_organizer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='org_companyID',
            field=models.CharField(max_length=15),
        ),
    ]
