# Generated by Django 4.2.7 on 2024-03-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_organizer_org_companyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_acitiv',
            new_name='user_activ',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=15),
        ),
    ]
